@url = test.gedis.cmd
@name = any
name = ""
comment = ""
schemacode = ""

@url = test.gedis.serverschema
@name = cmds
cmds = (LO) !test.gedis.cmd

@url = test.gedis.cmd1
@name = cmd
cmd = (O) !test.gedis.cmd
cmd2 = (O) !test.gedis.cmd

